#!/usr/bin/env python3
"""Deterministic synthetic dataset generator for the MERFISHEYES test databank.

Produces datasets in every format the app supports, with a fixed RNG seed so the
same (cells, genes, seed) always yields byte-stable counts and gene names. The
E2E manifest (tests/data/manifest.json) records the expected counts/genes that
these datasets are guaranteed to have.

Formats mirror exactly what the in-app adapters parse (verified against the
existing synthetic benchmark data):
  h5ad             AnnData: X (dense), obs[leiden,celltype], obsm[X_spatial,(X_umap)], var index
  xenium           cells.csv + features.tsv + cell_feature_matrix/{barcodes.tsv,matrix.mtx.gz}
  merscope         cell_metadata.csv + cell_by_gene.csv + cell_categories.csv
  single-molecule  parquet: feature_name,x_location,y_location[,z_location]

Usage:
  python scripts/testdata/generate.py --format all --cells 300 --genes 40 --out tests/data/tiny
  python scripts/testdata/generate.py --format h5ad --cells 50000 --genes 500 --out tests/data/generated/medium
"""

import argparse
import csv
import gzip
import os
from pathlib import Path

import numpy as np

CELLTYPES = [
    "Astrocyte", "Neuron", "Microglia", "Oligodendrocyte", "Endothelial",
    "Fibroblast", "Pericyte", "T_Cell", "B_Cell", "Macrophage",
]


def make_arrays(n_cells: int, n_genes: int, dims: int, seed: int):
    """Build the shared coordinate/expression/label arrays used by every format."""
    rng = np.random.default_rng(seed)
    genes = [f"gene_{i}" for i in range(n_genes)]
    # Spatial coords in a realistic micron-ish range.
    coords = (rng.random((n_cells, dims), dtype=np.float32) - 0.5) * 2000.0
    # Sparse-ish expression: ~10% non-zero, rounded to 2 decimals.
    expr = rng.random((n_cells, n_genes), dtype=np.float32)
    expr[expr < 0.9] = 0.0
    expr = np.round(expr * 3.0, 2).astype(np.float32)
    n_clusters = min(20, max(2, n_cells // 20))
    leiden = np.array([f"cluster_{rng.integers(0, n_clusters)}" for _ in range(n_cells)])
    celltype = np.array([CELLTYPES[rng.integers(0, len(CELLTYPES))] for _ in range(n_cells)])
    umap = (rng.random((n_cells, 2), dtype=np.float32) - 0.5) * 20.0
    return genes, coords, expr, leiden, celltype, umap


def write_h5ad(out: Path, n_cells, n_genes, dims, seed, sparse_x=False):
    import anndata as ad
    import pandas as pd

    genes, coords, expr, leiden, celltype, umap = make_arrays(n_cells, n_genes, dims, seed)
    obs = pd.DataFrame(
        {
            "leiden": pd.Categorical(leiden),
            "celltype": pd.Categorical(celltype),
        },
        index=[f"cell_{i}" for i in range(n_cells)],
    )
    var = pd.DataFrame(index=genes)
    # NOTE: the app's local H5adAdapter only reads a DENSE X for gene expression
    # (it has no CSR/CSC path), so raw-h5ad fixtures default to dense. `sparse_x`
    # is only used when this h5ad is an intermediate fed to the chunked pipeline
    # (which reads it in Python, where sparse keeps the temp file small).
    if sparse_x:
        from scipy import sparse

        X = sparse.csr_matrix(expr)
    else:
        X = expr
    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.obsm["X_spatial"] = coords
    adata.obsm["X_umap"] = umap
    out.parent.mkdir(parents=True, exist_ok=True)
    adata.write_h5ad(out)
    return out


def write_xenium(out_dir: Path, n_cells, n_genes, dims, seed):
    genes, coords, expr, leiden, celltype, _ = make_arrays(n_cells, n_genes, dims, seed)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(out_dir / "cells.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["cell_id", "x_centroid", "y_centroid", "leiden", "celltype"])
        for i in range(n_cells):
            w.writerow([i, round(float(coords[i, 0]), 4), round(float(coords[i, 1]), 4),
                        leiden[i], celltype[i]])

    with open(out_dir / "features.tsv", "w") as f:
        f.write("gene\n")
        f.write("\n".join(genes) + "\n")

    mtx_dir = out_dir / "cell_feature_matrix"
    mtx_dir.mkdir(exist_ok=True)
    with open(mtx_dir / "barcodes.tsv", "w") as f:
        f.write("\n".join(f"cell_{i}" for i in range(n_cells)) + "\n")

    # MatrixMarket: genes x cells, 1-based coordinates of non-zeros.
    nz = np.argwhere(expr.T > 0)  # (gene, cell)
    with gzip.open(mtx_dir / "matrix.mtx.gz", "wt") as f:
        f.write("%%MatrixMarket matrix coordinate real general\n")
        f.write("% Generated by MERFISHEYES test databank generator\n")
        f.write(f"{n_genes} {n_cells} {len(nz)}\n")
        for g, c in nz:
            f.write(f"{g + 1} {c + 1} {expr[c, g]}\n")
    return out_dir


def write_merscope(out_dir: Path, n_cells, n_genes, dims, seed):
    genes, coords, expr, leiden, celltype, _ = make_arrays(n_cells, n_genes, dims, seed)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(out_dir / "cell_metadata.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["EntityID", "center_x", "center_y"])
        for i in range(n_cells):
            w.writerow([i, round(float(coords[i, 0]), 4), round(float(coords[i, 1]), 4)])

    with open(out_dir / "cell_by_gene.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["cell"] + genes)
        for i in range(n_cells):
            w.writerow([i] + [expr[i, j] if expr[i, j] else 0 for j in range(n_genes)])

    with open(out_dir / "cell_categories.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["EntityID", "leiden", "celltype"])
        for i in range(n_cells):
            w.writerow([i, leiden[i], celltype[i]])
    return out_dir


def write_single_molecule(out: Path, n_genes, dims, seed, n_molecules):
    import pandas as pd

    rng = np.random.default_rng(seed + 1)
    genes = [f"gene_{i}" for i in range(n_genes)]
    feature = np.array(genes)[rng.integers(0, n_genes, n_molecules)]
    cols = {
        "feature_name": feature,
        "x_location": ((rng.random(n_molecules) - 0.5) * 2000.0).astype(np.float32),
        "y_location": ((rng.random(n_molecules) - 0.5) * 2000.0).astype(np.float32),
    }
    if dims == 3:
        cols["z_location"] = ((rng.random(n_molecules) - 0.5) * 50.0).astype(np.float32)
    out.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(cols).to_parquet(out, index=False)
    return out


def write_chunked(out_dir: Path, n_cells, n_genes, dims, seed):
    """Generate an intermediate h5ad and run the production chunking pipeline.

    Chunked output loads via ChunkedDataAdapter (lazy gene fetch), which is how
    the app serves large single-cell data — no 1GB in-memory matrix in the
    browser. The intermediate h5ad is written sparse (small) and removed after.
    """
    import subprocess
    import sys
    import tempfile

    process_script = Path(__file__).resolve().parents[1] / "process_spatial_data.py"
    if not process_script.exists():
        raise FileNotFoundError(f"process_spatial_data.py not found at {process_script}")

    out_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_h5ad = Path(tmp) / "intermediate.h5ad"
        write_h5ad(tmp_h5ad, n_cells, n_genes, dims, seed, sparse_x=True)
        subprocess.run(
            [sys.executable, str(process_script), str(tmp_h5ad), str(out_dir), "--format", "h5ad"],
            check=True,
        )
    return out_dir


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--format", required=True,
                   choices=["h5ad", "xenium", "merscope", "single-molecule", "chunked", "all"])
    p.add_argument("--sparse", action="store_true", help="write h5ad X as sparse CSR (advanced)")
    p.add_argument("--cells", type=int, default=300)
    p.add_argument("--genes", type=int, default=40)
    p.add_argument("--molecules", type=int, default=5000, help="single-molecule only")
    p.add_argument("--dims", type=int, default=2, choices=[2, 3])
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--out", required=True, help="output dir (folder formats) or base dir (all)")
    p.add_argument("--name", default=None, help="basename (default derived from size)")
    args = p.parse_args()

    out = Path(args.out)
    name = args.name or f"sc_{args.cells}c_{args.genes}g"

    if args.format in ("h5ad", "all"):
        path = write_h5ad(out / "h5ad" / f"{name}.h5ad" if args.format == "all" else out,
                          args.cells, args.genes, args.dims, args.seed, sparse_x=args.sparse)
        print(f"  h5ad            -> {path}")
    if args.format == "chunked":
        path = write_chunked(out, args.cells, args.genes, args.dims, args.seed)
        print(f"  chunked         -> {path}")
    if args.format in ("xenium", "all"):
        path = write_xenium(out / "xenium" / name if args.format == "all" else out,
                            args.cells, args.genes, args.dims, args.seed)
        print(f"  xenium          -> {path}")
    if args.format in ("merscope", "all"):
        path = write_merscope(out / "merscope" / name if args.format == "all" else out,
                              args.cells, args.genes, args.dims, args.seed)
        print(f"  merscope        -> {path}")
    if args.format in ("single-molecule", "all"):
        path = write_single_molecule(
            out / "single-molecule" / f"{name}.parquet" if args.format == "all" else out,
            args.genes, args.dims, args.seed, args.molecules)
        print(f"  single-molecule -> {path}")


if __name__ == "__main__":
    main()
