import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import path from "path";

import {
  progressiveOrder,
  progressiveSlots,
} from "@/lib/utils/progressive-order";

describe("progressiveOrder", () => {
  it("is a permutation of 0..n-1", () => {
    for (const n of [0, 1, 2, 3, 5, 8, 17, 1000, 4096]) {
      const order = Array.from(progressiveOrder(n));

      expect(order).toHaveLength(n);
      expect([...order].sort((a, b) => a - b)).toEqual(
        Array.from({ length: n }, (_, i) => i),
      );
    }
  });

  it("spreads every prefix over the whole range", () => {
    // The point of the order: a partially streamed gene must cover the whole
    // slide. With molecules in spatial order, the first 1/8 of the file must
    // still touch every eighth of the range.
    const n = 8192;
    const order = progressiveOrder(n);
    const prefix = Array.from(order.subarray(0, n / 8));
    const buckets = new Set(prefix.map((i) => Math.floor((i / n) * 8)));

    expect(buckets.size).toBe(8);

    // …and each eighth gets roughly its share (within 2x of the mean).
    const counts = new Array(8).fill(0);

    for (const i of prefix) counts[Math.floor((i / n) * 8)]++;
    const mean = prefix.length / 8;

    for (const c of counts) {
      expect(c).toBeGreaterThan(mean / 2);
      expect(c).toBeLessThan(mean * 2);
    }
  });

  // Both pipelines must emit byte-identical gene files, so the two
  // implementations of the permutation have to agree exactly. The golden file
  // is generated by progressive_order() in process_single_molecule.py.
  it("matches the Python pipeline's order exactly", () => {
    const golden = JSON.parse(
      readFileSync(
        path.join(__dirname, "..", "fixtures", "progressive-order.json"),
        "utf-8",
      ),
    ) as Record<string, number[]>;

    for (const [n, expected] of Object.entries(golden)) {
      expect(Array.from(progressiveOrder(Number(n)))).toEqual(expected);
    }
  });
});

describe("progressiveSlots", () => {
  it("is the inverse of progressiveOrder", () => {
    for (const n of [0, 1, 2, 3, 5, 9, 17, 1000]) {
      const order = progressiveOrder(n);
      const slots = progressiveSlots(n);

      for (let i = 0; i < n; i++) expect(slots[order[i]]).toBe(i);
    }
  });

  it("scattering by slots equals gathering by order (what Python writes)", () => {
    // Python does out[i] = src[order[i]]; the browser fills as it reads, so it
    // must do out[slots[j]] = src[j] and land on the same bytes.
    const n = 9;
    const src = Array.from({ length: n }, (_, i) => i * 10);
    const order = progressiveOrder(n);
    const slots = progressiveSlots(n);
    const gathered = Array.from(order, (o) => src[o]);
    const scattered = new Array(n);

    for (let j = 0; j < n; j++) scattered[slots[j]] = src[j];

    expect(scattered).toEqual(gathered);
  });
});
